# Generated by Django 6.0.1 on 2026-06-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.routine')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('time', models.TimeField()),
                ('action_type', models.CharField(choices=[('Check-In', 'Check-In'), ('Check-Out', 'Check-Out')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='routine.attendance')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.teacher')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('teacher', 'routine', 'date'), name='unique_teacher_routine_attendance_date'),
        ),
    ]
