# Generated by Django 6.0.1 on 2026-06-20 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_attendance_attendanceaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='routine.routine')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['routine__day', 'routine__start_time', 'student__username'],
                'constraints': [models.UniqueConstraint(fields=('routine', 'student'), name='unique_student_routine_enrollment')],
            },
        ),
    ]
