# Generated by Django 6.0.1 on 2026-09-11 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_routineenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab')], default='Theory', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='routine',
            name='section',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='routine',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routine.teacher'),
        ),
        migrations.AddField(
            model_name='routine',
            name='room_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='routine.room'),
        ),
        migrations.CreateModel(
            name='RoutineRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('sessions_per_week', models.PositiveSmallIntegerField()),
                ('required_room_type', models.CharField(blank=True, choices=[('Theory', 'Theory'), ('Lab', 'Lab')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=30)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('start_time', 'end_time'), name='unique_timeslot_range')],
            },
        ),
        migrations.AddField(
            model_name='routine',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='routine.timeslot'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher__isnull', False), ('time_slot__isnull', False)), fields=('teacher', 'day', 'time_slot'), name='unique_teacher_day_slot'),
        ),
        migrations.AddConstraint(
            model_name='routine',
            constraint=models.UniqueConstraint(condition=models.Q(('room_ref__isnull', False), ('time_slot__isnull', False)), fields=('room_ref', 'day', 'time_slot'), name='unique_room_day_slot'),
        ),
    ]
