# Generated by Django 6.0.1 on 2026-09-11 21:46

from django.db import migrations


def backfill_rooms_and_timeslots(apps, schema_editor):
    Routine = apps.get_model('routine', 'Routine')
    Room = apps.get_model('routine', 'Room')
    TimeSlot = apps.get_model('routine', 'TimeSlot')

    rooms_by_name = {}
    for room_name in Routine.objects.order_by().values_list('room', flat=True).distinct():
        if not room_name:
            continue
        room, _ = Room.objects.get_or_create(name=room_name, defaults={'room_type': 'Theory'})
        rooms_by_name[room_name] = room

    time_pairs = Routine.objects.order_by('start_time', 'end_time').values_list(
        'start_time', 'end_time'
    ).distinct()
    slots_by_pair = {}
    for order, (start_time, end_time) in enumerate(time_pairs):
        slot, _ = TimeSlot.objects.get_or_create(
            start_time=start_time,
            end_time=end_time,
            defaults={'order': order},
        )
        slots_by_pair[(start_time, end_time)] = slot

    for routine in Routine.objects.all():
        routine.room_ref = rooms_by_name.get(routine.room)
        routine.time_slot = slots_by_pair.get((routine.start_time, routine.end_time))
        routine.save(update_fields=['room_ref', 'time_slot'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_room_routine_section_alter_routine_teacher_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_rooms_and_timeslots, noop_reverse),
    ]
