# Generated by Django 6.0.1 on 2026-09-13 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_backfill_room_and_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='acronym',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='qualified_teachers', to='routine.course'),
        ),
        migrations.AlterField(
            model_name='routinerequirement',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routine.teacher'),
        ),
    ]
